### ISSUE TITLE
help me

### ISSUE THREAD

**Issue by Kiehyun** [guitar79/satellite#1]
satellite/OceanColor/DataOrder/

이 폴더에 위성자료 다운로드 하는 스크립트 작성중인데, 내가 너무 몰라서..
위성자료 주문하면 "http_manifest.txt" 이런 형태로 파일 링크가 오는데..
이 파일로 바로 다운로드 하는 스크립트좀 만들어줘~~

가급적 "http_manifest.txt" 이 파일 그대로 쓸수 있게 만들면 좋을듯...

**Comment by seungwonpark** [comment]
11e2537a2fe7afb949fe134d5b183d9e4e8d6a8f 커밋에서 에러 손봤습니다.

이슈를 닫겠습니다.
